[Port] Adamantine crossbreeds
SinguloStation13/SinguloStation13-Archived pull request #18
Opened 2021-02-17 03:00 UTC by MaltVinegar

## About The Pull Request

Ports adamantine crossbreeds from Bee https://github.com/BeeStation/BeeStation-Hornet/pull/2946

## Why It's Good For The Game

Players wanted it

## Changelog
:cl:
add: adds adamantine crossbreeds
/:cl:

2021-02-20 06:54 UTC, MaltVinegar commented
Fug

2021-02-21 10:33 UTC, TheOneAndMightyRed requested changes

2021-02-21 10:33 UTC, Redory commented on singulostation/code/modules/research/xenobiology/crossbreeding/_misc.dm
> +	icon = 'icons/obj/slimecrossing.dmi'
```suggestion
	icon = 'singulostation/icons/obj/slimecrossing.dmi'
```

2021-02-21 10:33 UTC, Redory commented on singulostation/code/modules/research/xenobiology/crossbreeding/_misc.dm
> +	icon = 'icons/obj/slimecrossing.dmi'
Object is not showing

2021-02-21 10:33 UTC, Redory commented on singulostation/code/modules/research/xenobiology/crossbreeding/_structures.dm
> +	icon = 'icons/obj/slimecrossing.dmi'
```suggestion
	icon = 'singulostation/icons/obj/slimecrossing.dmi'
```

2021-02-21 10:33 UTC, Redory commented on singulostation/code/modules/research/xenobiology/crossbreeding/_structures.dm
> +	icon = 'icons/obj/slimecrossing.dmi'
Icon not showing

2021-02-21 10:33 UTC, Redory commented on singulostation/code/modules/research/xenobiology/crossbreeding/_structures.dm
> +	stored_mutation = pick(mutation_list)
[10:51:43] Runtime in _structures.dm,461: pick() from empty list
  proc name: attack hand (/obj/structure/slime_crystal/green/attack_hand)
  usr: Guest-1435260588/(Lauren Beail)
  usr.loc: (Arrival Shuttle Hallway (63, 150, 2))

pick(empty list) causes a runtime here.
Happens, well, when you don't have any mutations and use it.

2021-02-21 10:33 UTC, TheOneAndMightyRed commented on singulostation/code/modules/research/xenobiology/crossbreeding/_structures.dm
> +	var/mob/living/simple_animal/pet/chosen_pet = pick(/mob/living/simple_animal/pet/dog/corgi,/mob/living/simple_animal/pet/dog/pug,/mob/living/simple_animal/pet/fox,/mob/living/simple_animal/pet/cat/k
```suggestion
	var/mob/living/simple_animal/pet/chosen_pet = pick(/mob/living/simple_animal/pet/dog/corgi,/mob/living/simple_animal/pet/dog/pug,/mob/living/simple_animal/pet/fox,/mob/living/simple_animal/pet/cat/kitten,/mob/living/simple_animal/pet/cat/space)
```

2021-02-21 10:33 UTC, TheOneAndMightyRed commented on singulostation/code/modules/research/xenobiology/crossbreeding/_structures.dm
> +	var/mob/living/simple_animal/pet/chosen_pet = pick(/mob/living/simple_animal/pet/dog/corgi,/mob/living/simple_animal/pet/dog/pug,/mob/living/simple_animal/pet/fox,/mob/living/simple_animal/pet/cat/k
Penguin and the default pet do not have icons

2021-02-21 10:33 UTC, TheOneAndMightyRed commented on singulostation/code/modules/research/xenobiology/crossbreeding/_structures.dm
> +	chosen_pet = new chosen_pet(get_turf(human_mob))
Making a rainbow slime pylon with both having bluespace and gold in it would fail to put chosen_pet in the affected_mobs list.
A simple `affected_mobs[chosen_pet] = 0` should hopefully fix that.

2021-02-21 10:33 UTC, TheOneAndMightyRed commented on singulostation/code/modules/research/xenobiology/crossbreeding/crystalized.dm
> +	qdel(src)
spamming Z would effectively make a bunch of these on the same tile.
Maybe do another
```
var/obj/structure/slime_crystal/C = locate() in range(6,get_turf(user))
if(C)
	return
```
after the do_after check to prevent duplication and stacking of pylons.

2021-02-21 10:35 UTC, TheOneAndMightyRed requested changes

2021-02-21 10:35 UTC, TheOneAndMightyRed commented on singulostation/code/modules/research/xenobiology/crossbreeding/_structures.dm
> +	icon = 'icons/obj/slimecrossing.dmi'
Wrong icon

2021-02-21 10:35 UTC, TheOneAndMightyRed commented on singulostation/code/modules/research/xenobiology/crossbreeding/crystalized.dm
> +	icon_state = "crystalline"
insert a `icon =` with the new file path

2021-02-27 12:06 UTC, Urumasi requested changes

2021-02-27 12:06 UTC, Urumasi commented on singulostation/code/modules/research/xenobiology/crossbreeding/_structures.dm
>  		gas.parse_gas_string(OPENTURF_DEFAULT_ATMOS)
```suggestion
		gas.parse_gas_string("o2=22;n2=82") // Put this in a constant somewhere
```

2021-02-27 12:06 UTC, Urumasi commented on singulostation/code/modules/research/xenobiology/crossbreeding/_structures.dm
> +			air_update_turf()
```suggestion
			T.air_update_turf()
```

2021-03-03 11:57 UTC, MaltVinegar commented
test

2021-03-03 11:57 UTC, MaltVinegar commented
test

2021-03-03 12:01 UTC, MaltVinegar commented
test

2021-03-03 12:04 UTC, MaltVinegar commented
test

2021-03-03 12:13 UTC, MaltVinegar commented
test

2021-03-03 12:14 UTC, MaltVinegar commented
test

2021-03-14 22:52 UTC, merged