Plastic flap and holofirelock nerfs
SinguloStation13/SinguloStation13-Archived pull request #19
Opened 2021-02-17 03:21 UTC by MaltVinegar

## About The Pull Request

Makes holofirelocks decay after an hour (you can see how long you have left by examining it) and makes plastic flaps impassible to humans

## Why It's Good For The Game

Use. fucking. AACs.

## Changelog
:cl:
tweak: Holofans now decay
tweak: No more going through plastic flaps
/:cl:

2021-02-20 20:32 UTC, TheOneAndMightyRed requested changes

2021-02-20 20:32 UTC, TheOneAndMightyRed commented on singulostation/code/game/objects/structures/holosign.dm
> +	. += "<span class='notice'>The holofan will decay in [timeleft(timerid)/10] seconds.</span>"
```suggestion
	. = ..()
	var/time_left = timeleft(timerid)
	var/time_type = ""
	if(time_left <= 1 MINUTES) //Less than one minute - count in seconds
		time_left = CEILING(time_left, 1 SECONDS) //Round it up to full seconds. Don't want decimals in our text
		time_type = "second"
		if(time_left != 1 SECONDS)
			time_type = "seconds"
		time_left /= 1 SECONDS
	else //Count in minutes
		time_left = CEILING(time_left, 1 MINUTES)
		time_type = "minute"
		if(time_left != 1 MINUTES)
			time_type = "minutes"
		time_left /= 1 MINUTES
	. += "<span class='notice'>The holofan will decay in [time_left] [time_type].</span>"
```

2021-02-20 20:32 UTC, TheOneAndMightyRed commented on singulostation/code/game/objects/structures/holosign.dm
> +	. += "<span class='notice'>The holofan will decay in [timeleft(timerid)/10] seconds.</span>"
Maybe change it up to this to make it show full minutes only and then only show seconds at the last minute?

2021-02-20 20:32 UTC, TheOneAndMightyRed commented on code/game/objects/structures/plasticflaps.dm
> +			. = FALSE //Singulo edit - nerfs holofans and plastic flaps
```suggestion
		if(ishuman(A)) //Singulo edit - nerfs holofans and plastic flaps
			. = FALSE //Singulo edit - nerfs holofans and plastic flaps
```

2021-02-20 20:32 UTC, TheOneAndMightyRed commented on code/game/objects/structures/plasticflaps.dm
> +			. = FALSE //Singulo edit - nerfs holofans and plastic flaps
Maybe let monkeys and xenomorphs through them?
Monkeys are inferior to humans so maybe let them pass through?
Also xenomorph because reasons.

2021-02-20 20:32 UTC, TheOneAndMightyRed commented on singulostation/code/game/objects/structures/holosign.dm
> +	var/duration = 60 MINUTES
Aah yes perfect amount of time you chose there. 👍

2021-02-20 20:38 UTC, MaltVinegar commented on singulostation/code/game/objects/structures/holosign.dm
> +	. += "<span class='notice'>The holofan will decay in [timeleft(timerid)/10] seconds.</span>"
Seems a bit pointless to me tbh

2021-02-21 13:38 UTC, TheOneAndMightyRed commented on singulostation/code/game/objects/structures/holosign.dm
> +	. += "<span class='notice'>The holofan will decay in [timeleft(timerid)/10] seconds.</span>"
Yeah it's just fluff to make it more readable. Instead of saying "2756.3 seconds", it will say "46 minutes".

2021-03-04 10:01 UTC, Urumasi commented
Did you create holosign.dm without moving the definition from holosign.dm, splitting the object definition into 2 places? Thank you, very cool

2021-03-04 13:59 UTC, TheOneAndMightyRed commented
Might be worth putting comments at the start of both files saying "//See singulostation/code/blabla.dm" in the future

2021-03-05 03:24 UTC, MaltVinegar commented
> Did you create holosign.dm without moving the definition from the original place, splitting the object definition into 2 places? Thank you, very cool
> Edit: I assume you do this to separate original wasp code from our singulo code changes, but will this actually improve the quality of the codebase? Nobody else does it like this

It makes it easier to update to the latest version of White Sands

2021-03-05 13:48 UTC, Urumasi commented
In that case this looks good

2021-03-08 03:46 UTC, merged