Slime crystals bugfix
SinguloStation13/SinguloStation13-Archived pull request #60
Opened 2021-06-01 20:08 UTC by ZombieNub

## About The Pull Request

This PR fixes issue #27 by limiting the number of materials that can be added to sheets based on the amount that those sheets already have, while making sure that the slime crystals are never wasted.

## Why It's Good For The Game

This prevents sheet stacks from having more materials than intended.

## Changelog
:cl:
fix: fixed cerulean slime crystals going over sheet stack maximums
/:cl:

2021-06-01 20:09 UTC, KubeRoot commented
Should this maybe create another stack of items when going over the limit?

2021-06-01 20:12 UTC, ZombieNub commented
I can't see why not, but I have limited BYOND coding experience, so I don't know how to achieve that. Might be rather simple, however.

2021-06-01 21:06 UTC, ZombieNub commented
I'm going to make KubeRoot's suggested change. Wish me luck.

2021-06-01 22:24 UTC, ZombieNub commented
This wound up being much simpler than I had anticipated. In total only one line needs changing and I'm surprised it wasn't already done. This should work with all stackable types.

2021-06-01 22:26 UTC, KubeRoot commented
1. This will always create a new stack, never add to the existing stack, correct?
2. Can the amount created be higher than the maximum stack size? In that case, will it perhaps go over the limit?

2021-06-01 22:28 UTC, ZombieNub commented
In my testing, the creation of new stacks accounts for both. Creating a new stack fills any other stacks on the same tile, and going over the maximum simply creates another stack.

2021-06-01 23:38 UTC, KubeRoot commented
> Creating a new stack fills any other stacks on the same tile

What if you're holding the stack in your hand/in an inventory?

2021-06-02 00:28 UTC, ZombieNub commented
It, unfortunately, does not add to the stack, but it does deposit the items on the floor. We can re-add the previous code to add full functionality.

2021-06-04 19:34 UTC, Urumasi requested changes

2021-06-04 19:34 UTC, Urumasi commented on singulostation/code/modules/research/xenobiology/crossbreeding/_misc.dm
> +	new target.type(get_turf(target), amt)
```suggestion
    if(amt > 0)
	    new target.type(get_turf(target), amt)
```
Using a poly-crystal on a stack that doesn't fill up creates a stack on the floor with 0 sheets.

2021-06-04 19:34 UTC, Urumasi commented on singulostation/code/modules/research/xenobiology/crossbreeding/_misc.dm
> +    amt -= amt_to_add
```suggestion
	stack_item.add(amt_to_add)
	amt -= amt_to_add
```
`error: inconsistent indentation`

2021-06-04 20:16 UTC, Urumasi commented on singulostation/code/modules/research/xenobiology/crossbreeding/_misc.dm
> +	    new target.type(get_turf(target), amt)
```suggestion
	if(amt > 0)
		new target.type(get_turf(target), amt)
```

2021-06-04 22:29 UTC, Urumasi approved these changes

2021-06-04 22:38 UTC, merged

2021-06-05 15:13 UTC, KubeRoot commented
Oh wait... there's no singulostation edit comments