Ports long-range analyzer from bee 2: electric boogaloo
SinguloStation13/SinguloStation13-Archived pull request #9
Opened 2021-02-02 18:40 UTC by Tulenich

## About The Pull Request

Adds a long-range analyzer with a _**brand new awful sprite!**_

## Why It's Good For The Game

It's a useful tool or something idk kuberoot was asking for it

## Changelog
:cl:
add: A new long-range analyzer with an awful sprite
tweak: A long-range analyzer now spawns in the CE's toolbelt instead of a regular one
tweak: A long-range analyzer is now researchable and craftable in engi- and scilathe
/:cl:

2021-02-02 22:29 UTC, MaltVinegar requested changes
I am able to scan things that are out of sight

2021-02-03 04:59 UTC, Tulenich commented
Fine, I'll try to fix it

2021-02-12 01:46 UTC, MaltVinegar requested changes

2021-02-12 01:46 UTC, MaltVinegar commented on singulostation/code/game/objects/items/devices/scanners.dm
> +/proc/los_check(mob/user, atom/target)
A. This doesn't even work and B. why not use an already existing LoS check?

2021-02-16 03:08 UTC, MaltVinegar commented
OP doesn't want to do it anymore

2021-02-16 03:08 UTC, closed without merging